apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instances }}
  storage:
    size: 1Gi
  superuserSecret:
    name: cluster-{{ include "cnpg-cluster.fullname" . }}-superuser
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cluster-{{ include "cnpg-cluster.fullname" . }}-app-user
  backup:
    barmanObjectStore:
      destinationPath: "postgres/{{ include "cnpg-cluster.fullname" . }}"
      endpointURL: sarvent-backups.nyc3.digitaloceanspaces.com
      s3Credentials:
        accessKeyId:
          name: cluster-{{ include "cnpg-cluster.fullname" . }}-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cluster-{{ include "cnpg-cluster.fullname" . }}-s3
          key: ACCESS_SECRET_KEY
