apiVersion: v1
data:
  username: cG9zdGdyZXM= # postgres
  password: cGFzc3dvcmQ= # password
kind: Secret
metadata:
  name: cluster-{{ include "cnpg-cluster.fullname" . }}-superuser
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  username: YXBw # app
  password: cGFzc3dvcmQ= # password
kind: Secret
metadata:
  name: cluster-{{ include "cnpg-cluster.fullname" . }}-app-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  ACCESS_KEY_ID: RE8wMEgzQkJHSlYyVFBHOTRQTlk=
  ACCESS_KEY_SECRET: dk9nWGN4UEc1VWJkQ1RFdTNRZWRaT0NuOFNmZlMxWEptK0w1TklqMTVoZw==
kind: Secret
metadata:
  name: cluster-{{ include "cnpg-cluster.fullname" . }}-s3
type: kubernetes.io/basic-auth
